name: "Discord Commits"
description: "Send commit summary to Discord using custom templates"
branding:
        icon: "bell"
        color: "purple"
inputs:
        webhook:
                description: "https://discord.com/api/webhooks/1145788482233585724/ASG7bfuNCrEYqUd-6f8mBECuUigDN-IAa7LjnIzB9fCMA5w7M9twwBbYwZZFXSqPLs9-/github"
                required: true
        message:
                description: "Nova Documentação Disponível."
        embed:
                description: "JSON string that accepts double braces for templates. Defaults to template's embed template"
        include-extras:
                description: "Boolean - Include extra embeds provided from templates."
        template:
                description: "The name of of a premade template."
        last-commit-only:
                description: true
